---
date: 2017-04-10
section_name: 산업
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: 9단21
profile: 7x15_9단21_5
section_id: 75
page_columns: 7
grid_size:
- 146.99664257142854
- 96.377964
lines_per_grid: 7
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 5
  - 6
- - 5
  - 0
  - 2
  - 6
- - 0
  - 6
  - 3
  - 4
- - 0
  - 10
  - 2
  - 5
- - 2
  - 10
  - 1
  - 5
- - 3
  - 6
  - 4
  - 9
  - 광고_9단21
article_line_thickness: 0.3
draw_divider: 
