---
date: 2017-04-10
section_name: 1면
is_front_page: true
grid_size:
- 137.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 1
  - 7
  - 5
- - 0
  - 6
  - 4
  - 4
- - 4
  - 6
  - 3
  - 4
- - 0
  - 10
  - 7
  - 5
  - :광고: 5단통
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 4
- 20.0
