---
date: 2017-04-10
section_name: 금융-3단기고
is_front_page: false
:ad_type: no_ad
page_columns: 7
grid_size:
- 147.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 4
- 25.51
story_frames:
- - 0
  - 0
  - 5
  - 7
- - 5
  - 0
  - 2
  - 7
- - 0
  - 7
  - 3
  - 8
- - 3
  - 7
  - 4
  - 3
- - 3
  - 10
  - 4
  - 3
- - 3
  - 13
  - 4
  - 2
