---
section_name: 책소개
page_heading_margin_in_lines: 4
ad_type: no_ad
is_front_page: 
profile: 6x15_9
section_id: 109
page_columns: 6
grid_size:
- 171.49608299999997
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 8
- - 4
  - 0
  - 2
  - 3
- - 4
  - 3
  - 2
  - 3
- - 4
  - 6
  - 2
  - 3
- - 0
  - 8
  - 4
  - 4
- - 3
  - 8
  - 1
  - 7
- - 4
  - 9
  - 2
  - 3
- - 0
  - 12
  - 4
  - 3
- - 4
  - 12
  - 2
  - 3
article_line_thickness: 0.3
draw_divider: 
