---
date: 2017-04-10
section_name: 정책
is_front_page: false
:ad_type: no_ad
grid_size:
- 137.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 4
  - 9
- - 4
  - 0
  - 3
  - 5
- - 4
  - 5
  - 3
  - 4
- - 0
  - 9
  - 4
  - 4
- - 4
  - 9
  - 3
  - 2
- - 0
  - 13
  - 4
  - 2
- - 4
  - 11
  - 1
  - 4
- - 5
  - 11
  - 2
  - 4
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 4
- 20.0
