---
date: 2017-04-10
section_name: 국제통일면
is_front_page: false
:ad_type: no_ad
page_columns: 5
grid_size:
- 196.362
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 2
- 20.0
story_frames:
- - 0
  - 0
  - 5
  - 5
- - 5
  - 0
  - 2
  - 5
- - 0
  - 5
  - 3
  - 5
- - 3
  - 5
  - 3
  - 2
- - 3
  - 8
  - 3
  - 2
- - 6
  - 5
  - 1
  - 5
