---
section_name: 국제통일면
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 5x15_6
section_id: 24
page_columns: 5
grid_size:
- 205.79529959999996
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 5
  - 5
- - 5
  - 0
  - 2
  - 5
- - 0
  - 5
  - 3
  - 5
- - 3
  - 5
  - 3
  - 2
- - 6
  - 5
  - 1
  - 5
- - 3
  - 8
  - 3
  - 2
article_line_thickness: 0.3
draw_divider: 
