---
date: 2017-04-10
section_name: 산업
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: no_ad
page_columns: 6
grid_size:
- 171.49666666666667
- 97.32266666666668
lines_per_grid: 7
width: 1114.02
height: 1544.88
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
draw_divider: 
story_frames:
- - 0
  - 0
  - 3
  - 7
- - 3
  - 0
  - 3
  - 4
- - 3
  - 4
  - 3
  - 3
- - 0
  - 7
  - 2
  - 3
- - 2
  - 7
  - 2
  - 4
- - 4
  - 7
  - 2
  - 4
- - 0
  - 10
  - 2
  - 3
- - 0
  - 13
  - 2
  - 2
- - 2
  - 11
  - 1
  - 4
- - 3
  - 11
  - 3
  - 2
- - 3
  - 13
  - 3
  - 2
article_line_thickness: 0.3
