---
section_name: 산업
page_heading_margin_in_lines: 3
ad_type: 5단통
is_front_page: false
profile: 6x15_5단통_2
section_id: 79
page_columns: 6
grid_size:
- 171.496083
- 96.377964
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 3
  - 10
- - 3
  - 0
  - 3
  - 10
- - 0
  - 10
  - 6
  - 5
  - 광고_5단통
article_line_thickness: 0.3
draw_divider: 
