---
date: 2017-04-10
section_name: 책소개
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: no_ad
profile: 6x15_7
section_id: 108
page_columns: 6
grid_size:
- 171.49608299999997
- 96.377964
lines_per_grid: 7
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 7
- - 4
  - 0
  - 2
  - 6
- - 4
  - 5
  - 2
  - 4
- - 0
  - 7
  - 4
  - 5
- - 4
  - 9
  - 2
  - 3
- - 0
  - 12
  - 4
  - 3
- - 4
  - 12
  - 2
  - 3
article_line_thickness: 0.3
draw_divider: 
