---
section_name: 산업
page_heading_margin_in_lines: 3
ad_type: 5단통
is_front_page: false
profile: 7x15_5단통_5
section_id: 213
page_columns: 7
grid_size:
- 146.99664257142854
- 97.322834551181
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755905511811
story_frames:
- - 0
  - 0
  - 5
  - 5
- - 5
  - 0
  - 2
  - 5
- - 0
  - 5
  - 3
  - 5
- - 3
  - 5
  - 2
  - 5
- - 5
  - 5
  - 2
  - 5
- - 0
  - 10
  - 7
  - 5
  - 광고_5단통
article_line_thickness: 0.3
draw_divider: 
