---
section_name: 산업
page_heading_margin_in_lines: 3
ad_type: 5단통
is_front_page: false
profile: 7x15_5단통_7
section_id: 84
page_columns: 7
grid_size:
- 146.996642571429
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 5
- - 4
  - 0
  - 3
  - 6
- - 0
  - 5
  - 3
  - 2
- - 3
  - 5
  - 1
  - 5
- - 4
  - 6
  - 2
  - 4
- - 6
  - 6
  - 1
  - 4
- - 0
  - 7
  - 3
  - 3
- - 0
  - 10
  - 7
  - 5
  - 광고_5단통
article_line_thickness: 0.3
draw_divider: 
