---
date: 2017-04-10
section_name: 1면
is_front_page: true
page_heading_margin_in_lines: 3
:ad_type: 5단통
profile: 7x15_H_5단통_4
section_id: 1
page_columns: 7
grid_size:
- 146.99664257142854
- 96.377964
lines_per_grid: 7
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 1
  - 4
  - 6
- - 4
  - 1
  - 3
  - 5
- - 0
  - 7
  - 4
  - 3
- - 4
  - 6
  - 3
  - 4
- - 0
  - 10
  - 7
  - 5
  - 광고_5단통
article_line_thickness: 0.3
draw_divider: 
