---
date: 2017-04-10
section_name: 오피니언
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: 5단통
page_columns: 6
grid_size:
- 171.49666666666667
- 97.32266666666668
lines_per_grid: 7
width: 1114.02
height: 1544.88
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
draw_divider: 
story_frames:
- - 0
  - 0
  - 4
  - 5
- - 4
  - 0
  - 2
  - 10
- - 0
  - 5
  - 4
  - 5
- - 0
  - 10
  - 6
  - 5
  - :광고: 5단통
article_line_thickness: 0.3
