---
section_name: 책소개
page_heading_margin_in_lines: 4
ad_type: no_ad
is_front_page: 
profile: 6x15_9
section_id: 111
page_columns: 6
grid_size:
- 171.49608299999997
- 96.377964
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 6
- - 4
  - 0
  - 2
  - 5
- - 0
  - 6
  - 4
  - 4
- - 4
  - 5
  - 2
  - 4
- - 0
  - 10
  - 4
  - 3
- - 4
  - 9
  - 2
  - 4
- - 0
  - 13
  - 2
  - 2
- - 2
  - 13
  - 2
  - 2
- - 4
  - 13
  - 2
  - 2
article_line_thickness: 0.3
draw_divider: 
