---
section_name: 기획
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_6
section_id: 218
page_columns: 7
grid_size:
- 146.99664257142854
- 96.377964
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 10
- - 4
  - 0
  - 3
  - 4
- - 4
  - 4
  - 3
  - 6
- - 0
  - 10
  - 4
  - 5
- - 2
  - 13
  - 2
  - 2
- - 4
  - 10
  - 3
  - 5
article_line_thickness: 0.3
draw_divider: 
