---
section_name: 1면
page_heading_margin_in_lines: 3
ad_type: 5단통
is_front_page: true
profile: 6x15_H_5단통_4
section_id: 10
page_columns: 6
grid_size:
- 171.49608299999997
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 1
  - 4
  - 6
- - 4
  - 1
  - 2
  - 5
- - 4
  - 6
  - 2
  - 4
- - 0
  - 7
  - 4
  - 3
- - 0
  - 10
  - 6
  - 5
  - 광고_5단통
article_line_thickness: 0.3
draw_divider: 
