---
date: 2017-04-10
section_name: 정치
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: no_ad
profile: 6x15_7
section_id: 30
page_columns: 6
grid_size:
- 171.49608299999997
- 96.377964
lines_per_grid: 7
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 6
  - 5
- - 0
  - 5
  - 4
  - 5
- - 4
  - 5
  - 2
  - 5
- - 0
  - 10
  - 1
  - 5
- - 1
  - 10
  - 3
  - 5
- - 4
  - 10
  - 2
  - 5
- - 4
  - 13
  - 2
  - 2
article_line_thickness: 0.3
draw_divider: 
