---
date: 2017-04-10
section_name: 정책
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: no_ad
page_columns: 6
grid_size:
- 171.49666666666667
- 97.32266666666668
lines_per_grid: 7
width: 1114.02
height: 1544.88
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
draw_divider: 
story_frames:
- - 0
  - 0
  - 3
  - 9
- - 3
  - 0
  - 3
  - 10
- - 0
  - 9
  - 6
  - 6
article_line_thickness: 0.3
