---
section_name: 산업
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 6x15_12
section_id: 93
page_columns: 6
grid_size:
- 171.496083
- 96.377964
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 2
  - 4
- - 2
  - 0
  - 2
  - 4
- - 4
  - 0
  - 2
  - 4
- - 0
  - 4
  - 2
  - 4
- - 2
  - 4
  - 2
  - 4
- - 4
  - 4
  - 2
  - 4
- - 0
  - 8
  - 2
  - 4
- - 2
  - 8
  - 2
  - 4
- - 4
  - 8
  - 2
  - 4
- - 0
  - 12
  - 2
  - 3
- - 2
  - 12
  - 2
  - 3
- - 4
  - 12
  - 2
  - 3
article_line_thickness: 0.3
draw_divider: 
