---
date: 2017-04-10
section_name: 금융-3단기고
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: no_ad
page_columns: 7
grid_size:
- 146.99714285714285
- 97.32266666666668
lines_per_grid: 7
width: 1114.02
height: 1544.88
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
draw_divider: 
story_frames:
- - 0
  - 0
  - 5
  - 7
- - 5
  - 0
  - 2
  - 7
- - 0
  - 7
  - 3
  - 8
- - 3
  - 7
  - 4
  - 3
- - 3
  - 10
  - 4
  - 3
- - 3
  - 13
  - 4
  - 2
article_line_thickness: 0.3
