---
section_name: 1면
page_heading_margin_in_lines: 3
ad_type: 광고없음
is_front_page: false
profile: 6x15_광고없음_5
section_id: 313
page_columns: 6
grid_size:
- 171.49606299212348
- 97.32283464566807
lines_per_grid: 7.0
width: 1114.01574803148
height: 1544.88188976376
left_margin: 42.5196850393695
top_margin: 42.5196850393695
right_margin: 42.5196850393695
bottom_margin: 42.5196850393695
gutter: 12.7559055118108
story_frames:
- - 0
  - 1
  - 3
  - 3
  - :extended: 7
- - 3
  - 1
  - 3
  - 4
  - :kind: 사진
    :extended: 2
    :images:
    - :position: 3
      :column: 2
      :row: 2
- - 0
  - 4
  - 3
  - 4
  - :pushed: 7
- - 3
  - 5
  - 3
  - 5
  - :pushed: 2
    :graphics:
    - :position: '2'
      :extra_height_in_lines: -3
      :column: 2
      :row: 2
- - 0
  - 8
  - 3
  - 2
article_line_thickness: 0.3
draw_divider: 
