---
section_name: 책소개
page_heading_margin_in_lines: 4
ad_type: no_ad
is_front_page: 
profile: 7x15_9
section_id: 112
page_columns: 7
grid_size:
- 146.996642571429
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 5
  - 6
- - 5
  - 0
  - 2
  - 3
- - 5
  - 3
  - 2
  - 3
- - 0
  - 6
  - 4
  - 5
- - 4
  - 6
  - 1
  - 9
- - 5
  - 6
  - 2
  - 3
- - 5
  - 9
  - 2
  - 3
- - 0
  - 11
  - 4
  - 4
- - 5
  - 12
  - 2
  - 3
article_line_thickness: 0.3
draw_divider: 
