---
section_name: 실험
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 6x15_2
section_id: 129
page_columns: 6
grid_size:
- 171.49608299999997
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 4
- - 4
  - 0
  - 2
  - 4
article_line_thickness: 0.3
draw_divider: 
