---
section_name: 정치
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_8
section_id: 14
page_columns: 7
grid_size:
- 146.99664257142854
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 6
  - 8
- - 6
  - 0
  - 1
  - 6
- - 6
  - 6
  - 1
  - 5
- - 0
  - 8
  - 2
  - 4
- - 2
  - 8
  - 4
  - 4
- - 6
  - 11
  - 1
  - 4
- - 0
  - 12
  - 2
  - 3
- - 2
  - 12
  - 4
  - 3
article_line_thickness: 0.3
draw_divider: 
