---
date: 2017-04-10
section_name: 국제통일면
is_front_page: false
:ad_type: no_ad
grid_size:
- 196.362
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 4
  - 10
- - 4
  - 0
  - 3
  - 4
- - 4
  - 4
  - 3
  - 3
- - 4
  - 7
  - 3
  - 3
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 2
- 20.0
