---
section_name: 정치
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 6x15_7
section_id: 148
page_columns: 6
grid_size:
- 171.49608299999997
- 97.322834551181
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755905511811
story_frames:
- - 0
  - 0
  - 6
  - 5
- - 0
  - 5
  - 3
  - 5
- - 3
  - 5
  - 3
  - 5
- - 0
  - 10
  - 2
  - 3
- - 0
  - 13
  - 2
  - 2
- - 2
  - 10
  - 2
  - 5
- - 4
  - 10
  - 2
  - 5
article_line_thickness: 0.3
draw_divider: 
