---
date: 2017-04-10
section_name: 책소개
is_front_page: false
:ad_type: no_ad
page_columns: 7
grid_size:
- 134.65
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 4
- 25.51
story_frames:
- - 0
  - 0
  - 5
  - 6
- - 5
  - 0
  - 2
  - 3
- - 5
  - 3
  - 2
  - 3
- - 0
  - 6
  - 4
  - 5
- - 0
  - 11
  - 4
  - 4
- - 4
  - 6
  - 1
  - 9
- - 5
  - 6
  - 2
  - 3
- - 5
  - 9
  - 2
  - 3
- - 5
  - 12
  - 2
  - 3
