# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
# test:
#   <<: *default
#   database: db/test.sqlite3
#
# production:
#   <<: *default
#   database: db/production.sqlite3

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: mskim
  password:

development:
  <<: *default
  database: style_guide_development
  username: mskim

test:
  <<: *default
  database: style_guide__test
  username: mskim

production:
  <<: *default
  database: style_guide_production
  username: mskim
