---
date: 2017-04-10
section_name: 금융-4단기고
is_front_page: false
:ad_type: no_ad
page_columns: 7
grid_size:
- 134.65
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 4
- 25.51
story_frames:
- - 0
  - 0
  - 4
  - 4
- - 4
  - 0
  - 3
  - 4
- - 0
  - 4
  - 4
  - 4
- - 4
  - 4
  - 3
  - 7
- - 0
  - 8
  - 4
  - 7
- - 4
  - 11
  - 3
  - 4
