---
section_name: 산업
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_10
section_id: 86
page_columns: 7
grid_size:
- 146.99664257142854
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 5
  - 5
- - 5
  - 0
  - 2
  - 3
- - 5
  - 3
  - 2
  - 5
- - 0
  - 5
  - 2
  - 5
- - 2
  - 5
  - 3
  - 4
- - 5
  - 8
  - 2
  - 3
- - 2
  - 9
  - 3
  - 6
- - 0
  - 10
  - 2
  - 3
- - 5
  - 11
  - 2
  - 4
- - 0
  - 13
  - 2
  - 2
article_line_thickness: 0.3
draw_divider: 
