---
section_name: 1면
page_heading_margin_in_lines: 3
ad_type: 광고없음
is_front_page: false
profile: 7x15_광고없음_4
section_id: 310
page_columns: 7
grid_size:
- 146.99662542182
- 97.3228346456681
lines_per_grid: 7.0
width: 1114.01574803148
height: 1544.88188976376
left_margin: 42.5196850393695
top_margin: 42.5196850393695
right_margin: 42.5196850393695
bottom_margin: 42.5196850393695
gutter: 12.7559055118108
story_frames:
- - 0
  - 1
  - 4
  - 6
  - :extended: -11
- - 4
  - 1
  - 3
  - 5
  - :kind: 사진
    :extended: -1
    :images:
    - :position: 3
      :column: 2
      :row: 2
- - 4
  - 6
  - 3
  - 4
  - :pushed: -1
- - 0
  - 7
  - 4
  - 3
  - :pushed: -11
    :graphics:
    - :position: '2'
      :extra_height_in_lines: 6
      :column: 2
      :row: 1
article_line_thickness: 0.3
draw_divider: 
