---
date: 2017-04-10
section_name: 애드버토리얼
is_front_page: false
:ad_type: no_ad
grid_size:
- 161.96833333333333
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 2
  - 4
- - 2
  - 0
  - 2
  - 4
- - 4
  - 0
  - 2
  - 4
- - 0
  - 4
  - 2
  - 4
- - 2
  - 4
  - 2
  - 4
- - 4
  - 4
  - 2
  - 4
- - 0
  - 8
  - 2
  - 4
- - 2
  - 8
  - 2
  - 4
- - 4
  - 8
  - 2
  - 4
- - 0
  - 12
  - 2
  - 3
- - 2
  - 12
  - 2
  - 3
- - 4
  - 12
  - 2
  - 3
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 3
- 20.0
