---
date: 2017-04-10
section_name: 책소개
is_front_page: false
:ad_type: no_ad
grid_size:
- 161.96833333333333
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 6
  - 6
- - 0
  - 6
  - 4
  - 7
- - 4
  - 6
  - 2
  - 7
- - 0
  - 13
  - 1
  - 2
- - 1
  - 13
  - 1
  - 2
- - 2
  - 13
  - 1
  - 2
- - 3
  - 13
  - 1
  - 2
- - 4
  - 13
  - 1
  - 2
- - 5
  - 13
  - 1
  - 2
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 3
- 20.0
