---
section_name: 국제통일
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 6x15_5
section_id: 154
page_columns: 6
grid_size:
- 171.49608299999997
- 97.322834551181
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755905511811
story_frames:
- - 0
  - 0
  - 6
  - 4
- - 0
  - 4
  - 1
  - 7
- - 1
  - 4
  - 5
  - 7
- - 0
  - 11
  - 1
  - 4
- - 1
  - 11
  - 5
  - 4
article_line_thickness: 0.3
draw_divider: 
