---
section_name: 산업
page_heading_margin_in_lines: 3
ad_type: 9단21
is_front_page: false
profile: 7x15_9단21_7
section_id: 85
page_columns: 7
grid_size:
- 146.99664257142854
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 2
  - 6
- - 2
  - 0
  - 2
  - 6
- - 4
  - 0
  - 3
  - 3
- - 4
  - 3
  - 3
  - 3
- - 0
  - 6
  - 4
  - 9
  - 광고_9단21
- - 4
  - 6
  - 3
  - 3
- - 4
  - 9
  - 3
  - 3
- - 4
  - 12
  - 3
  - 3
article_line_thickness: 0.3
draw_divider: 
