---
date: 2017-04-10
section_name: 책소개
is_front_page: false
:ad_type: 5단통
page_columns: 7
grid_size:
- 147.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 4
- 25.51
story_frames:
- - 0
  - 0
  - 5
  - 5
- - 5
  - 0
  - 2
  - 4
- - 0
  - 5
  - 3
  - 5
- - 3
  - 5
  - 2
  - 5
- - 5
  - 4
  - 2
  - 3
- - 5
  - 7
  - 2
  - 3
- - 0
  - 10
  - 7
  - 5
  - :광고: 5단통
