---
date: 2017-04-10
section_name: 오피니언
is_front_page: false
:ad_type: 5단통
grid_size:
- 161.96833333333333
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 6
  - 4
- - 0
  - 4
  - 3
  - 6
- - 3
  - 4
  - 3
  - 6
- - 0
  - 10
  - 6
  - 5
  - :광고: 5단통
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 3
- 20.0
