---
section_name: 정치
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_9
section_id: 142
page_columns: 7
grid_size:
- 146.99664257142854
- 97.322834551181
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755905511811
story_frames:
- - 0
  - 0
  - 5
  - 7
- - 5
  - 0
  - 2
  - 8
- - 0
  - 7
  - 4
  - 3
- - 0
  - 10
  - 4
  - 3
- - 4
  - 7
  - 1
  - 6
- - 5
  - 8
  - 2
  - 4
- - 0
  - 13
  - 2
  - 2
- - 2
  - 13
  - 3
  - 2
- - 5
  - 12
  - 2
  - 3
article_line_thickness: 0.3
draw_divider: 
