---
section_name: 전면광고
page_heading_margin_in_lines: 4
ad_type: 15단통
is_front_page: 
profile: 6x15_15단통_0
section_id: 106
page_columns: 6
grid_size:
- 171.496083
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 6
  - 15
  - 광고_15단통
article_line_thickness: 0.3
draw_divider: 
