---
date: 2017-04-10
section_name: 정치
is_front_page: false
:ad_type: no_ad
page_columns: 6
grid_size:
- 161.96833333333333
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 3
- 20.0
story_frames:
- - 0
  - 0
  - 6
  - 10
- - 0
  - 10
  - 2
  - 5
- - 2
  - 10
  - 2
  - 5
- - 4
  - 10
  - 2
  - 3
- - 4
  - 13
  - 2
  - 2
