---
section_name: 1면
page_heading_margin_in_lines: 3
ad_type: 5단통
is_front_page: true
profile: 6x15_H_5단통_5
section_id: 8
page_columns: 6
grid_size:
- 171.496083
- 96.377964
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 1
  - 4
  - 5
- - 4
  - 1
  - 2
  - 5
- - 0
  - 6
  - 3
  - 5
- - 3
  - 6
  - 1
  - 5
- - 4
  - 6
  - 2
  - 5
- - 0
  - 10
  - 6
  - 5
  - 광고_5단통
article_line_thickness: 0.3
draw_divider: 
