---
section_name: 정책
page_heading_margin_in_lines: 4
ad_type: no_ad
is_front_page: 
profile: 7x15_8
section_id: 101
page_columns: 7
grid_size:
- 146.996642571429
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 9
- - 4
  - 0
  - 3
  - 5
- - 4
  - 5
  - 3
  - 4
- - 0
  - 9
  - 4
  - 4
- - 4
  - 9
  - 3
  - 2
- - 4
  - 11
  - 1
  - 4
- - 5
  - 11
  - 2
  - 4
- - 0
  - 13
  - 4
  - 2
article_line_thickness: 0.3
draw_divider: 
