---
date: 2017-04-10
section_name: 정치
is_front_page: false
:ad_type: 9단21
grid_size:
- 137.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 7
  - 6
- - 0
  - 6
  - 3
  - 5
- - 0
  - 11
  - 3
  - 4
- - 2
  - 11
  - 1
  - 4
- - 3
  - 6
  - 4
  - 9
  - :광고: 9단21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 4
- 20.0
