---
date: 2017-04-10
section_name: 1면
is_front_page: true
:ad_type: no_ad
page_columns: 6
grid_size:
- 159.21666666666667
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 3
- 25.51
story_frames:
- - 0
  - 1
  - 4
  - 6
- - 0
  - 7
  - 4
  - 3
- - 4
  - 1
  - 2
  - 9
- - 0
  - 10
  - 6
  - 5
