---
section_name: 금융
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_8
section_id: 57
page_columns: 7
grid_size:
- 146.996642571429
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 7
  - 2
- - 0
  - 2
  - 4
  - 5
- - 4
  - 2
  - 3
  - 5
- - 0
  - 7
  - 2
  - 5
- - 2
  - 7
  - 2
  - 5
- - 4
  - 7
  - 3
  - 5
- - 0
  - 12
  - 4
  - 3
- - 4
  - 12
  - 3
  - 3
article_line_thickness: 0.3
draw_divider: 
