---
date: 2017-04-10
section_name: 금융-4단기고
is_front_page: false
:ad_type: no_ad
grid_size:
- 137.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
story_frames:
- - 0
  - 0
  - 4
  - 5
- - 4
  - 0
  - 3
  - 3
- - 0
  - 5
  - 2
  - 4
- - 2
  - 5
  - 2
  - 4
- - 4
  - 3
  - 3
  - 6
- - 0
  - 9
  - 4
  - 6
- - 4
  - 9
  - 3
  - 6
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 4
- 20.0
