---
section_name: 정책
page_heading_margin_in_lines: 4
ad_type: no_ad
is_front_page: 
profile: 7x15_3
section_id: 102
page_columns: 7
grid_size:
- 146.99664257142854
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 7
  - 7
- - 0
  - 7
  - 4
  - 8
- - 4
  - 7
  - 3
  - 8
article_line_thickness: 0.3
draw_divider: 
