---
date: 2017-04-10
section_name: 정책
is_front_page: false
:ad_type: no_ad
page_columns: 6
grid_size:
- 171.96833333333333
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 3
- 25.51
story_frames:
- - 0
  - 0
  - 6
  - 9
- - 0
  - 9
  - 4
  - 3
- - 4
  - 9
  - 2
  - 3
- - 0
  - 12
  - 2
  - 3
- - 2
  - 12
  - 2
  - 3
- - 4
  - 12
  - 2
  - 3
