---
section_name: 행정
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_8
section_id: 40
page_columns: 7
grid_size:
- 146.996642571429
- 96.377964
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 56.69292
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 5
  - 6
- - 5
  - 0
  - 2
  - 6
- - 0
  - 6
  - 4
  - 4
- - 0
  - 10
  - 4
  - 3
- - 4
  - 6
  - 1
  - 7
- - 5
  - 6
  - 2
  - 9
- - 0
  - 13
  - 2
  - 2
- - 2
  - 13
  - 3
  - 2
article_line_thickness: 0.3
draw_divider: 
