---
section_name: 정치
page_heading_margin_in_lines: 3
ad_type: 9단21
is_front_page: false
profile: 7x15_9단21_5
section_id: 22
page_columns: 7
grid_size:
- 146.996642571429
- 97.322846
lines_per_grid: 7.0
width: 1114.015878
height: 1544.88207
left_margin: 42.51969
top_margin: 42.51969
right_margin: 42.51969
bottom_margin: 42.51969
gutter: 12.755907
story_frames:
- - 0
  - 0
  - 4
  - 6
- - 4
  - 0
  - 3
  - 6
- - 0
  - 6
  - 3
  - 3
- - 3
  - 6
  - 4
  - 9
  - 광고_9단21
- - 0
  - 9
  - 3
  - 4
- - 0
  - 13
  - 3
  - 2
article_line_thickness: 0.3
draw_divider: 
