---
date: 2017-04-10
section_name: 정책
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: no_ad
profile: 6x15_13
section_id: 95
page_columns: 6
grid_size:
- 171.496083
- 96.377964
lines_per_grid: 7
width: 1114.0158780000002
height: 1544.88207
left_margin: 42.519690000000004
top_margin: 56.69292
right_margin: 42.519690000000004
bottom_margin: 42.519690000000004
gutter: 12.755907
draw_divider: false
story_frames:
- - 0
  - 0
  - 4
  - 4
- - 4
  - 0
  - 2
  - 3
- - 0
  - 4
  - 3
  - 3
- - 3
  - 4
  - 1
  - 3
- - 4
  - 3
  - 2
  - 5
- - 0
  - 7
  - 2
  - 3
- - 0
  - 10
  - 2
  - 3
- - 2
  - 7
  - 2
  - 4
- - 4
  - 7
  - 2
  - 4
- - 0
  - 13
  - 2
  - 2
- - 2
  - 11
  - 2
  - 4
- - 4
  - 11
  - 2
  - 2
- - 4
  - 13
  - 2
  - 2
article_line_thickness: 0.3
